services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    env_file:
      - ./gateway/.env
    ports:
      - "8080:8080"
    restart: on-failure
    profiles:
      - game
      - user
      - all

  game:
    container_name: game
    build:
      context: ./game
    env_file:
      - ./game/.env
    ports:
      - "8081:8080"
    restart: on-failure
    profiles:
      - game
      - all

  gacha:
    container_name: gacha
    build:
      context: ./gacha
    env_file:
      - ./gacha/.env
    ports:
      - "8082:8080"
    restart: on-failure
    volumes:
      - gacha_data:/var/lib/sparxie/gacha
    profiles:
      - game
      - all

  inventory:
    container_name: inventory
    build:
      context: ./inventory
    env_file:
      - ./inventory/.env
    ports:
      - "8083:8080"
    restart: on-failure
    profiles:
      - game
      - all

  shop:
    container_name: shop
    build:
      context: ./shop
    env_file:
      - ./shop/.env
    ports:
      - "8084:8080"
    restart: on-failure
    profiles:
      - game
      - all

  user:
    container_name: user
    build:
      context: ./user
    env_file:
      - ./user/.env
    ports:
      - "8085:8080"
    restart: on-failure
    profiles:
      - user
      - all

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    ports:
      - "9092:9092" # Internal (Docker)
      - "9094:9094" # External (Host)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    profiles:
      - user
      - game
      - all

volumes:
  gacha_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${GACHA_DATA_PATH}"
