services:
  gacha:
    container_name: gacha
    build:
      context: ./gacha
    env_file:
      - gacha/.env
    ports:
      - "8082:8080"
    restart: on-failure
    volumes:
      - ./gacha/data:/var/lib/sparxie/gacha

  game:
    container_name: game
    build:
      context: ./game
    ports:
      - "8081:8080"
    restart: on-failure
    depends_on:
      - gacha

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - game
