spring:
  application:
    name: shop
  data:
    redis:
      database: ${REDIS_DATABASE:2}
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  mongodb:
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin&replicaSet=rs0
    representation:
      uuid: standard

app:
  flamingock:
    database: ${MONGO_DATABASE}
