spring:
  application:
    name: shop
  data:
    redis:
      database: ${REDIS_DATABASE}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mongodb:
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin&replicaSet=rs0
    representation:
      uuid: standard

app:
  flamingock:
    database: ${MONGO_DATABASE}
