package io.lexi115.sparxie.user.exceptions;

public enum ErrorCode {
    ERR_USER_NOT_FOUND,
    ERR_USER_ALREADY_EXISTS,
    ERR_USERNAME_ALREADY_IN_USE,
    ERR_INVALID_CREDENTIALS,
    ERR_INVALID_REFRESH_TOKEN,
    ERR_AUTHENTICATION_ERROR,
    ERR_VALIDATION_FAILED,
    ERR_INTERNAL_SERVER_ERROR,
    ERR_METHOD_NOT_SUPPORTED
}
