spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Game
            - id: game
              uri: ${GAME_SERVICE_BASE_URI:http://game:8080}
              predicates:
                - Path=/api/game/**
              filters:
                - StripPrefix=1
            # Banner
            - id: banner
              uri: ${BANNER_SERVICE_BASE_URI:http://game:8080}
              predicates:
                - Path=/api/banner/**
              filters:
                - StripPrefix=1
            # User
            - id: user
              uri: ${USER_SERVICE_BASE_URI:http://user:8080}
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=1
            # Authentication
            - id: auth
              uri: ${AUTH_SERVICE_BASE_URI:http://user:8080}
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
