spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: game
              uri: http://game:8080
              predicates:
                - Path=/api/game/**
              filters:
                - StripPrefix=1
