info:
  name: Consume items
  type: http
  seq: 5

http:
  method: POST
  url: "{{inventoryBaseUri}}/inventories/{{userId}}/consume"
  body:
    type: json
    data: |-
      {
        "transactionId": "{{$randomUUID}}",
        "playerId": "{{playerId}}",
        "items": {
          "{{itemId}}": {{itemAmount}}
        }
      }
  auth: inherit

runtime:
  variables:
    - name: playerId
      value: "{{userId}}"
    - name: itemId
      value: limited_ticket
    - name: itemAmount
      value: "10"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
