info:
  name: Consume items
  type: http
  seq: 2

http:
  method: POST
  url: "{{inventoryBaseUri}}/inventory/consume"
  body:
    type: json
    data: |-
      {
        "transactionId": "{{$randomUUID}}",
        "playerId": "{{playerId}}",
        "items": {
          "{{itemId}}": {{itemAmount}}
        }
      }
  auth: inherit

runtime:
  variables:
    - name: playerId
      value: 1bbad0cc-4a14-4c5e-8254-f851ffa30907
    - name: itemId
      value: oneiric_shard
    - name: itemAmount
      value: "1600"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
