spring:
  application:
    name: gacha
  cache:
    type: caffeine
    cache-names: banners, banner_templates
    caffeine:
      spec: expireAfterWrite=12h,maximumSize=1000
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.type.mapping: >
        USER_CREATED:io.lexi115.sparxie.gacha.player.event.PlayerCreatedEvent,
        USER_DELETED:io.lexi115.sparxie.gacha.player.event.PlayerDeletedEvent
    bootstrap-servers:
      - ${KAFKA_SERVER:kafka:9092}
  data:
    redis:
      database: ${REDIS_DATABASE:0}
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  storage:
    root-path: ${APP_STORAGE_ROOT:/var/lib/sparxie/gacha}
    banners-path: ${app.storage.root-path}/banners
  kafka:
    topic:
      user: user-topic
    group:
      gacha: gacha-group
