info:
  name: Get player materials
  type: http
  seq: 2

http:
  method: GET
  url: "{{gatewayBaseUri}}/api/inventories/materials?page={{page}}"
  params:
    - name: page
      value: "{{page}}"
      type: query
    - name: size
      value: "{{size}}"
      type: query
      disabled: true
  auth:
    type: bearer
    token: "{{accessToken}}"

runtime:
  variables:
    - name: page
      value: "0"
    - name: size
      value: "1"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
