package io.lexi115.sparxie.game.exceptions;

public enum ErrorCode {
    ERR_WARP_LOCKED,
    ERR_SHOP_LOCKED,
    ERR_INVENTORY_LOCKED,
    ERR_PLAYER_NOT_FOUND,
    ERR_BANNER_NOT_FOUND,
    ERR_CHARACTER_NOT_FOUND,
    ERR_WEAPON_NOT_FOUND,
    ERR_MATERIAL_NOT_FOUND,
    ERR_SHOP_ITEM_NOT_FOUND,
    ERR_NOT_ENOUGH_ITEMS,
    ERR_VALIDATION_FAILED,
    ERR_ILLEGAL_ARGUMENT,
    ERR_METHOD_NOT_SUPPORTED
}
