spring:
  application:
    name: game
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers:
      - ${KAFKA_SERVER}

app:
  http:
    client-uri:
      warp: ${WARP_CLIENT_URI}
      banners: ${BANNER_CLIENT_URI}
      inventories: ${INVENTORY_CLIENT_URI}
      characters: ${CHARACTER_CLIENT_URI}
      weapons: ${WEAPON_CLIENT_URI}
      materials: ${MATERIAL_CLIENT_URI}
      shop: ${SHOP_CLIENT_URI}
  kafka:
    topic:
      warp: warp-topic
      shop: shop-topic
