spring:
  application:
    name: game
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers:
      - ${KAFKA_SERVER:kafka:9092}

app:
  http:
    client-uri:
      warp: ${WARP_CLIENT_URI:http://gacha:8080/warp}
      banner: ${BANNER_CLIENT_URI:http://gacha:8080/banner}
      inventory: ${INVENTORY_CLIENT_URI:http://inventory:8080/inventory}
      shop: ${SHOP_CLIENT_URI:http://shop:8080/shop}
  kafka:
    topic:
      warp: warp-topic
      shop: shop-topic
